"""
Migrate data from JSON files to Supabase PostgreSQL database.

This script:
1. Reads existing projects.json and repositories.json
2. Migrates data to Supabase tables
3. Preserves relationships (project-repository M:N)
4. Migrates nested data (tasks, milestones, stats)
"""
import json
import sys
from pathlib import Path
from datetime import datetime

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.db.supabase_client import get_supabase
from dotenv import load_dotenv

load_dotenv()

def safe_int(value, default=0):
    """Safely convert value to integer."""
    if value is None:
        return default
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        # Remove commas and convert
        try:
            return int(value.replace(",", ""))
        except (ValueError, AttributeError):
            return default
    return default

def map_status(old_status):
    """Map old status values to new schema constraints."""
    status_map = {
        "Cloned": "cloned",
        "Pending": "pending",
        "Analyzing": "analyzing",
        "Analyzed": "analyzed",
        "Error": "error",
        "Cloning": "cloning"
    }
    return status_map.get(old_status, "pending")

def map_project_status(old_status):
    """Map old project status values to new schema constraints."""
    status_map = {
        "active": "active",
        "Active": "active",
        "inactive": "inactive",
        "Inactive": "inactive",
        "archived": "archived",
        "Archived": "archived",
        "planning": "planning",
        "Planning": "planning"
    }
    return status_map.get(old_status, "active")

def migrate_repositories():
    """Migrate repositories from JSON to Supabase."""
    print("\n" + "=" * 60)
    print("MIGRATING REPOSITORIES")
    print("=" * 60)
    
    supabase = get_supabase()
    
    # Load JSON data
    json_path = Path(__file__).parent.parent / "data" / "repositories.json"
    
    if not json_path.exists():
        print(f"⚠️  No repositories.json found at {json_path}")
        return {}
    
    with open(json_path) as f:
        repositories = json.load(f)
    
    print(f"📦 Found {len(repositories)} repositories in JSON")
    
    # Map old IDs to new IDs
    id_mapping = {}
    
    for repo in repositories:
        old_id = repo["id"]
        
        # Prepare data for insert (with safe type conversions)
        repo_data = {
            "name": repo.get("name"),
            "url": repo.get("url"),
            "username": repo.get("username") or "",  # Handle NULL
            "main_branch": repo.get("main_branch", "main"),
            "status": map_status(repo.get("status", "pending")),
            "commit_analysis": repo.get("commit_analysis"),
            "repo_scan": repo.get("repo_scan"),
            "commits_count": safe_int(repo.get("commits_count")),
            "vulnerabilities_count": safe_int(repo.get("vulnerabilities_count")),
            # added_at will be auto-generated by database
        }
        
        # Insert repository (skip if already exists)
        try:
            result = supabase.table("repositories").insert(repo_data).execute()
            new_id = result.data[0]["id"]
            id_mapping[old_id] = new_id
            print(f"  ✅ Migrated: {repo['name']} (ID: {old_id} → {new_id})")
        except Exception as e:
            if "duplicate" in str(e).lower() or "unique" in str(e).lower():
                # Repository already exists, get its ID
                existing = supabase.table("repositories")\
                    .select("id")\
                    .eq("url", repo_data["url"])\
                    .execute()
                if existing.data:
                    new_id = existing.data[0]["id"]
                    id_mapping[old_id] = new_id
                    print(f"  ⏭️  Skipped (exists): {repo['name']} (ID: {old_id} → {new_id})")
            else:
                print(f"  ❌ Error migrating {repo['name']}: {e}")
                raise

    
    print(f"\n✅ Migrated {len(repositories)} repositories")
    return id_mapping


def migrate_projects(repo_id_mapping):
    """Migrate projects from JSON to Supabase."""
    print("\n" + "=" * 60)
    print("MIGRATING PROJECTS")
    print("=" * 60)
    
    supabase = get_supabase()
    
    # Load JSON data
    json_path = Path(__file__).parent.parent / "data" / "projects.json"
    
    if not json_path.exists():
        print(f"⚠️  No projects.json found at {json_path}")
        return
    
    with open(json_path) as f:
        projects = json.load(f)
    
    print(f"📦 Found {len(projects)} projects in JSON")
    
    for project in projects:
        old_id = project["id"]
        
        # Extract nested data
        tasks = project.pop("tasks", None)
        milestones = project.pop("milestones", None)
        stats = project.pop("stats", None)
        repository_ids = project.pop("repository_ids", [])
        
        # Prepare project data
        project_data = {
            "name": project.get("name"),
            "description": project.get("description"),
            "owner": project.get("owner"),
            "start_date": project.get("start_date"),
            "status": map_project_status(project.get("status", "active")),
        }
        
        # Insert project
        result = supabase.table("projects").insert(project_data).execute()
        new_project_id = result.data[0]["id"]
        
        print(f"\n  ✅ Migrated project: {project['name']} (ID: {old_id} → {new_project_id})")
        
        # Migrate project-repository relationships
        if repository_ids:
            relationships = []
            for old_repo_id in repository_ids:
                # Map old repo ID to new repo ID
                new_repo_id = repo_id_mapping.get(old_repo_id)
                if new_repo_id:
                    relationships.append({
                        "project_id": new_project_id,
                        "repository_id": new_repo_id
                    })
            
            if relationships:
                supabase.table("project_repositories").insert(relationships).execute()
                print(f"    ✅ Linked {len(relationships)} repositories")
        
        # Migrate tasks
        if tasks:
            task_count = 0
            for task in tasks:
                task_data = {
                    "id": task.get("id"),
                    "project_id": new_project_id,
                    "title": task.get("title"),
                    "status": task.get("status", "Todo"),
                    "assignee": task.get("assignee", "Unassigned"),
                    "priority": task.get("priority", "Medium"),
                    "due_date": task.get("due_date"),
                }
                
                try:
                    supabase.table("project_board_tasks").insert(task_data).execute()
                    task_count += 1
                except Exception as e:
                    print(f"    ⚠️  Failed to migrate task {task.get('id')}: {e}")
            
            if task_count > 0:
                print(f"    ✅ Migrated {task_count} tasks")
        
        # Migrate milestones
        if milestones:
            milestone_count = 0
            for milestone in milestones:
                # Convert old format to new format
                milestone_data = {
                    "project_id": new_project_id,
                    "label": milestone.get("label"),
                    "progress": milestone.get("progress", 0),
                    "start_date": milestone.get("date"),  # Old field was 'date'
                    "end_date": milestone.get("end_date"),
                }
                
                try:
                    supabase.table("project_milestones").insert(milestone_data).execute()
                    milestone_count += 1
                except Exception as e:
                    print(f"    ⚠️  Failed to migrate milestone {milestone.get('label')}: {e}")
            
            if milestone_count > 0:
                print(f"    ✅ Migrated {milestone_count} milestones")
        
        # Migrate stats
        if stats:
            stats_data = {
                "project_id": new_project_id,
                "active_issues": stats.get("active_issues", 0),
                "open_prs": stats.get("open_prs", 0),
                "contributors": stats.get("contributors", 0),
            }
            
            try:
                supabase.table("project_insights").insert(stats_data).execute()
                print(f"    ✅ Migrated project stats")
            except Exception as e:
                print(f"    ⚠️  Failed to migrate stats: {e}")
    
    print(f"\n✅ Migrated {len(projects)} projects")


def verify_migration():
    """Verify migration was successful."""
    print("\n" + "=" * 60)
    print("VERIFYING MIGRATION")
    print("=" * 60)
    
    supabase = get_supabase()
    
    # Count records
    projects_count = supabase.table("projects").select("count", count="exact").execute().count
    repos_count = supabase.table("repositories").select("count", count="exact").execute().count
    relationships_count = supabase.table("project_repositories").select("count", count="exact").execute().count
    tasks_count = supabase.table("project_board_tasks").select("count", count="exact").execute().count
    milestones_count = supabase.table("project_milestones").select("count", count="exact").execute().count
    
    print(f"📊 Projects: {projects_count}")
    print(f"📊 Repositories: {repos_count}")
    print(f"📊 Project-Repository Links: {relationships_count}")
    print(f"📊 Tasks: {tasks_count}")
    print(f"📊 Milestones: {milestones_count}")
    
    print("\n" + "=" * 60)
    print("✅ MIGRATION COMPLETE!")
    print("=" * 60)


def main():
    """Run the migration."""
    print("=" * 60)
    print("JSON TO SUPABASE MIGRATION")
    print("=" * 60)
    print(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    try:
        # Step 1: Migrate repositories first (to get ID mapping)
        repo_id_mapping = migrate_repositories()
        
        # Step 2: Migrate projects (with relationships)
        migrate_projects(repo_id_mapping)
        
        # Step 3: Verify
        verify_migration()
        
        print("\n✅ Migration completed successfully!")
        return True
        
    except Exception as e:
        print(f"\n❌ Migration failed: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
